<h1>Numpy 100 exercises<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#初学者10道" data-toc-modified-id="初学者10道-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>初学者10道</a></span></li><li><span><a href="#入门级10道" data-toc-modified-id="入门级10道-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>入门级10道</a></span></li></ul></div>

# 初学者10道

In [1]:
#1. 在python环境中导入numpy包，并命名为np
import numpy as np

In [2]:
#2. 查看numpy版本和配置信息
np.__version__

'1.13.3'

In [4]:
#3. 创建零向量，zeros函数
z = np.zeros((2,3))
z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [5]:
#4. 将上面的零向量的第二行第三列元素置为1。
#注意python中行列下班是从0开始。
z[1,2]=1
z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
#5. arange函数，创建一个在给定范围的向量。
np.arange(0,10,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [13]:
#6. reshape函数，将array变形为矩阵
np.arange(0,10,0.5).reshape(4,-1)

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5,  9. ,  9.5]])

In [14]:
#7. nonzero函数，寻找非0元素的下标
np.nonzero([1,2,3,0,0,4,0])

(array([0, 1, 2, 5], dtype=int64),)

In [15]:
#8. eye函数，生成单位矩阵
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [18]:
#9. diag函数，diagonal对角线。
np.diag([1,2,3,4],k=0)
#np.diag([1,2,3,4],k=1)
#np.diag([1,2,3,4],k=-1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
#10. random模块的random函数，生成随机数
np.random.random((3,3))

array([[ 0.28018876,  0.7521272 ,  0.54422254],
       [ 0.46682105,  0.61869709,  0.15360289],
       [ 0.73022722,  0.59582261,  0.82676252]])

# 入门级10道

In [28]:
#1. 创建一个8*8的“棋盘”矩阵
#0、2、4、6行&&1、3、5、7列的元素置为1
#1、3、5、7行&&0、2、4、6列的元素置为1 
z=np.zeros((8,8),dtype='int')

z[1::2,::2 ]=1
z[::2, 1::2]=1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [30]:
#2. min()、max()函数
z=np.random.random((6,6))
z.min(), z.max()

(0.0036504929870632141, 0.97798547587669726)

In [35]:
#3. 函数tile(A,reps),reps即重复的次数，
#不仅可以是数字，还可以是array。比如构造棋盘矩阵
np.tile(([[0,1],
          [-1,0]]),(2,4))

array([[ 0,  1,  0,  1,  0,  1,  0,  1],
       [-1,  0, -1,  0, -1,  0, -1,  0],
       [ 0,  1,  0,  1,  0,  1,  0,  1],
       [-1,  0, -1,  0, -1,  0, -1,  0]])

In [37]:
#4. 归一化，将矩阵规格化到0～1，
#即最小的变成0，最大的变成1，最小与最大之间的等比缩放
z=np.random.random((5,5))
z=(z-z.min())/(z.max()-z.min())
z

array([[ 0.55399888,  0.51681538,  0.52723421,  1.        ,  0.14264547],
       [ 0.8536444 ,  0.62708446,  0.21529835,  0.9344723 ,  0.01349011],
       [ 0.        ,  0.96611796,  0.55688571,  0.41057547,  0.30787366],
       [ 0.56501313,  0.70772484,  0.40922094,  0.66136865,  0.38643332],
       [ 0.03865788,  0.97397826,  0.2284003 ,  0.81438361,  0.05068343]])

In [38]:
#5. 矩阵点乘
np.dot(np.ones((5,3)), [[3,60]
                        , [52,23]
                        , [31,16]])

array([[ 86.,  99.],
       [ 86.,  99.],
       [ 86.,  99.],
       [ 86.,  99.],
       [ 86.,  99.]])

In [40]:
#6. 矩阵相加，5*5矩阵+1*5的向量，
#相当于每一行都加上1*5矩阵
z = np.ones((5,5))
z = z+range(5)
z

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [50]:
#7. linspace函数，在给定区间中生成均匀分布的给定个数。
#函数原型 linspace(start, stop, num=50, endpoint=True, retstep=False)
np.linspace(0,10,num=11,endpoint=True,retstep=False)
#生成0~10之间均匀分布的11个数，包括0和1。
#若endpoint=False,则10不包括在里面。
#若retstep=False，会同时返回均匀区间中每两个数的间隔。

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [80]:
#8. sort函数。调用random模块中的random函数生成10个随机数，然后sort排序。
z=np.random.randint(0,19,(7,7))
#sort(axis=-1, kind='quicksort', order=None)
z.sort(axis=0)
print(z)

[[ 0  2  2  3  2  4  0]
 [ 8  3  3  5  6  8  2]
 [ 8  6  3  6  7  9  4]
 [ 9  6  5  9  9 10  5]
 [ 9  7  5 11 11 11 15]
 [13 12 11 12 17 15 16]
 [14 14 15 17 18 17 17]]


In [81]:
#9. allclose函数，判断两个array在误差范围内是否相等
#函数原型allclose(a, b, rtol=1e-05, atol=1e-08)，
#若absolute(a - b) <= (atol + rtol * absolute(b))则相等
a=np.random.randint(0,5,10)
b=np.random.randint(0,5,10)
np.allclose(a,b)

False

In [82]:
#10. mean函数，求平均值
np.random.randint(0,15,10).mean()

6.5999999999999996