## 基本功能 重新索引

In [34]:
import numpy as np
from pandas import DataFrame, Series

print '重新指定索引及顺序'
obj = Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
print obj
obj2 = obj.reindex(['a', 'b', 'd', 'c', 'e'])
print obj2
print obj.reindex(['a', 'b', 'd', 'c', 'e'], fill_value = 0)  # 指定不存在元素的默认值
print

print '重新指定索引并指定填元素充方法'
obj3 = Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
print obj3
print obj3.reindex(range(6), method = 'ffill') #ffill和前值相同, bfill和后值相同
print


重新指定索引及顺序
d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
d    4.5
c    3.6
e    NaN
dtype: float64
a   -5.3
b    7.2
d    4.5
c    3.6
e    0.0
dtype: float64

重新指定索引并指定填元素充方法
0      blue
2    purple
4    yellow
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object



In [40]:
print '对DataFrame重新指定索引'
frame = DataFrame(np.arange(9).reshape(3, 3),
                  index = ['a', 'c', 'd'],
                  columns = ['Ohio', 'Texas', 'California'])
print frame
print '--------a, b, c, d--------'
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
print frame2
print

print '重新指定column'
states = ['Texas', 'Utah', 'California']
print frame.reindex(columns = states)
print

print '对DataFrame重新指定索引并指定填元素充方法'
print frame.reindex(index = ['a', 'b', 'c', 'd'],
                    method = 'ffill',
                    columns = states.sort())  #
print frame.loc[['a', 'b', 'd', 'c'], states]


对DataFrame重新指定索引
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
--------a, b, c, d--------
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

重新指定column
   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

对DataFrame重新指定索引并指定填元素充方法
   Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8
   California  Texas  Utah
a         2.0    1.0   NaN
b         NaN    NaN   NaN
d         8.0    7.0   NaN
c         5.0    4.0   NaN


## 基本功能 丢弃指定轴上的项
• 丢弃某条轴上的一个或多个项很简单，只要有一个索引数组或列表即可。由于 需要执行一些数据整理和集合逻辑，所以drop方法返回的是一个在指定轴上删 除了指定值的新对象

In [41]:
import numpy as np
from pandas import Series, DataFrame

print 'Series根据索引删除元素'
obj = Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
print new_obj
print obj.drop(['d', 'c'])
print

Series根据索引删除元素
a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
e    4.0
dtype: float64



In [46]:
print 'DataFrame删除元素，可指定索引或列。'
data = DataFrame(np.arange(16).reshape((4, 4)),
                  index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                  columns = ['one', 'two', 'three', 'four'])
print data
print '---------------drop(Colorado, Ohio)---------------'
print data.drop(['Colorado', 'Ohio'])
print '---------------drop(two, axis = 1)----------------'
print data.drop('two', axis = 1)
print '---------------drop([two, four], axis = 1)----------'
print data.drop(['two', 'four'], axis = 1)
print '----------------data #原数据并未改变--------------'
print data #原数据并未改变

DataFrame删除元素，可指定索引或列。
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
---------------drop(Colorado, Ohio)---------------
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15
---------------drop(two, axis = 1)----------------
          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15
---------------drop([two, four], axis = 1)----------
          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14
----------------data #原数据并未改变--------------
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


## 基本功能 索引、选取和过滤

In [48]:
import numpy as np
from pandas import Series, DataFrame

print 'Series的索引，默认数字索引可以工作。'
obj = Series(np.arange(4.), index = ['a', 'b', 'c', 'd']) #任然可以用传统的0,1,2,3...
print obj['b']
print obj[3]
print obj[[1, 3]]
print obj[obj < 2]
print

print 'Series的数组切片'
print obj['b':'c']  # 从'b'到'c'  非数字索引 闭区间 无法计算出开区间
obj['b':'c'] = 5
print obj
print

Series的索引，默认数字索引可以工作。
1.0
3.0
b    1.0
d    3.0
dtype: float64
a    0.0
b    1.0
dtype: float64

Series的数组切片
b    1.0
c    2.0
dtype: float64
a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64



In [56]:
?DataFrame.loc

In [22]:
print 'DataFrame的索引'
data = DataFrame(np.arange(16).reshape((4, 4)),
                  index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                  columns = ['one', 'two', 'three', 'four'])
print data
print data['two'] # 打印列
print data[['three', 'one']]
print data[:2]
print data.loc['Colorado', ['two', 'three']] # 指定索引和列
#print data.loc[['Colorado', 'Utah'], [3, 0, 1]] loc函数无法识别默认的数值索引[[3, 0, 1]]
#print data.loc[2]  # 打印第2行（从0开始）      loc函数无法识别默认的数值索引[2]
print data.loc[:'Utah', 'two'] # 从开始到Utah，第2列。
print

DataFrame的索引
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32
          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
two      5
three    6
Name: Colorado, dtype: int32
Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32



In [23]:
print '根据条件选择'
print data[data.three > 5]
print data < 5  # 打印True或者False
data[data < 5] = 0
print data

根据条件选择
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False
          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


## 基本功能 算术运算和数据对齐
• 对不同的索引对象进行算术运算 
• 自动数据对齐在不重叠的索引处引入了NA值，缺失值会在算术运算过程中传播。 
• 对于DataFrame，对齐操作会同时发生在行和列上。 
• fill_value参数 
• DataFrame和Series之间的运算

In [24]:
import numpy as np
from pandas import Series, DataFrame

print '加法'
s1 = Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])
print s1
print s2
print s1 + s2
print

加法
a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64
a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64



In [25]:
print 'DataFrame加法，索引和列都必须匹配。'
df1 = DataFrame(np.arange(9.).reshape((3, 3)),
                columns = list('bcd'),
                index = ['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12).reshape((4, 3)),
                columns = list('bde'),
                index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
print df1
print df2
print df1 + df2

DataFrame加法，索引和列都必须匹配。
            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11
            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN



In [26]:
print '数据填充'
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns = list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns = list('abcde'))
print df1
print df2
print df1.add(df2, fill_value = 0)
print df1.reindex(columns = df2.columns, fill_value = 0)

数据填充
     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0



In [32]:
print 'DataFrame与Series之间的操作'
arr = np.arange(12.).reshape((3, 4))
print arr
print arr[0]
print arr - arr[0]
print

frame = DataFrame(np.arange(12).reshape((4, 3)),
                  columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.loc['Utah']
print frame
print series
print frame - series
print

series2 = Series(range(3), index = list('bef'))
print frame + series2
series3 = frame['d']
print frame.sub(series3, axis = 0)  # 按列减  和缺失值做运算还等于缺失值

DataFrame与Series之间的操作
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
[ 0.  1.  2.  3.]
[[ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]
 [ 8.  8.  8.  8.]]

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11
b    0
d    1
e    2
Name: Utah, dtype: int32
        b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN
        b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1


## 基本功能 函数应用和映射
• numpy的ufuncs（元素级数组方法） 
• DataFrame的apply方法 
• 对象的applymap方法（因为Series有一个应用于元素级的map方法）

In [20]:
import numpy as np
from pandas import Series, DataFrame

print '函数'
frame = DataFrame(np.random.randn(4, 3),
                  columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
print frame
print np.abs(frame)
print

print 'applymap和map'
_format = lambda x: '%.2f' % x
print frame.applymap(_format)
print frame['e'].map(_format)


函数
               b         d         e
Utah    1.606706  0.322495 -0.524441
Ohio   -0.394166 -0.816525 -0.007542
Texas   0.313563 -0.551372 -1.797390
Oregon -0.792046  0.584041  1.255278
               b         d         e
Utah    1.606706  0.322495  0.524441
Ohio    0.394166  0.816525  0.007542
Texas   0.313563  0.551372  1.797390
Oregon  0.792046  0.584041  1.255278

applymap和map
            b      d      e
Utah     1.61   0.32  -0.52
Ohio    -0.39  -0.82  -0.01
Texas    0.31  -0.55  -1.80
Oregon  -0.79   0.58   1.26
Utah      -0.52
Ohio      -0.01
Texas     -1.80
Oregon     1.26
Name: e, dtype: object


In [21]:
print 'lambda以及应用'
f = lambda x: x.max() - x.min()
print frame.apply(f)
print frame.apply(f, axis = 1)
def f(x):
    return Series([x.min(), x.max()], index = ['min', 'max'])
print frame.apply(f)
print

lambda以及应用
b    2.398752
d    1.400566
e    3.052668
dtype: float64
Utah      2.131147
Ohio      0.808983
Texas     2.110952
Oregon    2.047324
dtype: float64
            b         d         e
min -0.792046 -0.816525 -1.797390
max  1.606706  0.584041  1.255278



## 基本功能 排序和排名
• 对行或列索引进行排序 
• 对于DataFrame，根据任意一个轴上的索引进行排序 
• 可以指定升序降序 
• 按值排序 
• 对于DataFrame，可以指定按值排序的列 
• rank函数

In [13]:
import numpy as np
from pandas import Series, DataFrame

print '根据索引排序，对于DataFrame可以指定轴。'
obj = Series(range(4), index = ['d', 'a', 'b', 'c'])
print obj.sort_index()
frame = DataFrame(np.arange(8).reshape((2, 4)),
                  index = ['three', 'one'],
                  columns = list('dabc'))
print frame.sort_index()
print frame.sort_index(axis = 1)
print frame.sort_index(axis = 1, ascending = False) # 降序
print

根据索引排序，对于DataFrame可以指定轴。
a    1
b    2
c    3
d    0
dtype: int64
       d  a  b  c
one    4  5  6  7
three  0  1  2  3
       a  b  c  d
three  1  2  3  0
one    5  6  7  4
       d  c  b  a
three  0  3  2  1
one    4  7  6  5



In [17]:
print '根据值排序'
obj = Series([4, 7, -3, 2])
print obj.sort_values() # order已淘汰
print

print 'DataFrame指定列排序'
frame = DataFrame({'b':[4, 7, -3, 2], 'a':[0, 1, 0, 1]})
print frame
print frame.sort_values(by = 'b') # sort_index(by = ...)已淘汰
print frame.sort_values(by = ['a', 'b'])
print

根据值排序
2   -3
3    2
0    4
1    7
dtype: int64

DataFrame指定列排序
   a  b
0  0  4
1  1  7
2  0 -3
3  1  2
   a  b
2  0 -3
3  1  2
0  0  4
1  1  7
   a  b
2  0 -3
0  0  4
3  1  2
1  1  7



In [19]:
print 'rank，求排名的平均位置(从1开始)'
obj = Series([7, -5, 7, 4, 2, 0, 4])
# 对应排名：-5(1), 0(2), 2(3), 4(4), 4(5), 7(6), 7(7)
print obj.rank() #先排名, 再计算所在排名数,如果有重复,计算平均值
print obj.rank(method = 'first')  # 去第一次出现，不求平均值。
print obj.rank(ascending = False, method = 'max') # 逆序，并取最大值。所以-5的rank是7.
print

frame = DataFrame({'b':[4.3, 7, -3, 2],
                  'a':[0, 1, 0, 1],
                  'c':[-2, 5, 8, -2.5]})
print '-------axis = 1-----------'
print frame
print frame.rank(axis = 1)

rank，求排名的平均位置(从1开始)
0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64
0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64
0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

-------axis = 1-----------
   a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5
     a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0


## 基本功能 带有重复值的索引
• 对于重复索引，返回Series，对应单个值的索引则返回标量

In [12]:
import numpy as np
from pandas import Series, DataFrame

print '重复的索引'
obj = Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])
print obj.index.is_unique # 判断是非有重复索引
print obj['a']#[0], obj.a[1]
df = DataFrame(np.random.randn(4, 3), index = ['a', 'a', 'b', 'b'])
print df
print df.loc['b', 0]
print df.loc['b', 1]


重复的索引
False
a    0
a    1
dtype: int64
          0         1         2
a  2.053676  0.346629 -0.250291
a  1.005104 -0.553517  0.693417
b -0.072086 -0.376578 -0.700723
b  0.687180 -0.664054  0.674252
b   -0.072086
b    0.687180
Name: 0, dtype: float64
b   -0.376578
b   -0.664054
Name: 1, dtype: float64
